parameters:
  queue.name: hello
  file_reader.file_name: urls.txt
  system.app_dir: /var/www/php

services:
  components\db\DB:
    class: components\db\DB
    factory: ['components\db\DB', 'getDb']
  contracts\repository\UrlStatisticRepositoryInterface:
    class: repository\UrlStatMariaDbRepository
    arguments:
      - '@components\db\DB'
  contracts\queue\QueueInterface:
    class: queue\Queue
    arguments: ['%queue.name%']
# TODO Use Autowire for next defenitions
  command\Receiver:
    class: command\Receiver
    arguments:
      - '@contracts\queue\QueueInterface'
      - '@contracts\repository\UrlStatisticRepositoryInterface'
  command\Sender:
    class: command\Sender
    arguments:
      - '@contracts\queue\QueueInterface'
      - '@contracts\fileReader\FileReaderInterface'
  contracts\fileReader\FileReaderInterface:
    class: components\fileReader\FileReaderArray
    arguments: ['%system.app_dir%', '%file_reader.file_name%']
